### PR TITLE
Auto dark mode example

### PR DESCRIPTION
**Pull request by nx10**
This PR changes the dark-mode example so that it automatically switches between light and dark mode depending on the users system/browser preference (using the [`prefers-color-scheme` CSS media feature](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)).

It's a very trivial edit and basically just wraps the dark mode theme in
```css
/* default (light) theme CSS */

@media (prefers-color-scheme: dark) {
  /* dark theme CSS */
}
```

chrome_yFx86pezQ9

Related to #210 .

I almost feel like this should be the default pdoc theme, but understand if it is out of scope.

### CODE REVIEW

**Comment by mhils** [comment]
Thanks for the PR! My main nuisance with this change is that people will visit https://pdoc.dev/docs/dark-mode/demo.html and it will not be dark. Is there a good way to fix that?

**Comment by nx10** [comment]
Ah I see, yeah I can't think of anything easy to fix that without adding bloat (e.g. adding some JavaScript that e.g. reads an URI parameter, or adding auto-dark-mode as a second example)

**Comment by nx10** [comment]
If you are generally interested in this as a default feature I can also work on a PR that adds a toggle (system default/light/dark) in the top right similar to the [furo sphinx theme](https://pradyunsg.me/furo/quickstart/)

**Comment by mhils** [comment]
Thanks! I do appreciate your effort here. Unfortunately dark mode adds a substantial amount of maintenance overhead, which is something I don't want to take on going forward. As the primary maintainer of pdoc, I don't want the additional burden of testing all changes with multiple color schemes. Thanks again for sending the initial PR, but I'd really like pdoc's scope small here.

**Comment by nx10** [comment]
I see, absolutely understandable. Thanks for your work!

**Pull request closed without merging**
