### PR TITLE
html template - show a "Module Index" in Index column

### PR DESCRIPTION
**Pull request by luv**
"Module Index" show the complete module hierarchy from the top-level package.
This should be useful for navigating.

### CODE REVIEW

**Comment by luv** [comment]
There are two issues with the code: 

* pdoc for a top-level module (ie. not a package) eg. `pdoc --html --html-dir test posixpath` generates an incorrect link
* pdoc only for an inner module eg. `pdoc --html --html-dir test xml.dom` generates broken links

**Comment by luv** [comment]
@BurntSushi ping

**Comment by BurntSushi** [comment]
@luv I'm not sure when I'll get to this. Regrettably, I made the mistake of not writing any tests, so the only way I can merge stuff is if I know it to be trivially correct or if I manually QA it. Changing how links are resolved is concerning, for example.

**Comment by luv** [comment]
Ok, I undestand, no probs, thanks.

Btw. the changes are basically only to the template (except one minor one which is actually irrelevant to my use-case) so I pass the modified template as an argument to pdoc and it works fine for me so I'm fine if this is not going to be merge/will take time.

**Comment by mostaphaRoudsari** [comment]
Thanks @luv! Worked pretty well.

@BurntSushi what is the best way to start writing tests for `pdoc`? That way it will be easier for you to make you decision and merge them.

**Comment by cortesi** [comment]
Hi there! This PR conflicts with master. I'll close this for now as part of our general cleanup. Please feel free to rebase this and to resubmit. Pdoc now has a new dev team, and we'll make sure your PR is actioned promptly.

**Pull request closed without merging**
