### PR TITLE
Adding support for markdown output

### PR DESCRIPTION
**Pull request by sanseihappa**

### CODE REVIEW

**Comment by BurntSushi** [comment]
@sanseihappa Awesome, thanks. At first blush, this looks pretty good.

@jvantuyl How much mileage can you get out of this?

**Comment by jvantuyl** [comment]
I haven't been able to run that code (on my phone right now), but...

Pros:

* Can embed in other doc systems. Very, very good.

Cons:

* Doesn't utilize markdown tables (which aren't always supported but are useful here).
* Can't pass through identifier information. This is primarily a concern for that glorious day that `pdoc` can autogenerate API docs for Sphinx.

Need To Check:

* Unclear if it's Unicode clean.

**Comment by sanseihappa** [comment]
@jvantuyl How would I utilize markdown tables?  My intent was simply to pass-through most of the docstrings with appropriate markdown headers for various sections.  There are a few places that code blocks are used, but other than that, it seems that markdown embedded in docstrings will pop up in the resulting output.  That allows usage of markdown tables within docstrings...

How to check if Unicode clean? Any tools I can run across it?

**Comment by sanseihappa** [comment]
@jvantuyl @BurntSushi Any decisions on merging this PR and rolling an incremental release?

**Comment by sanseihappa** [comment]
@jvantuyl @BurntSushi Any decisions on merging this PR?

**Comment by sanseihappa** [comment]
@BurntSushi Any decision on merging this PR?

**Comment by sanseihappa** [comment]
Hi, any updates to this PR?

**Comment by BurntSushi** [comment]
@sanseihappa Sorry it's taking so long. I'll get to it when I can. I need to pull and try it out for myself before I can let myself merge it.

**Comment by sanseihappa** [comment]
@BurntSushi Any update? :)

**Comment by BurntSushi** [comment]
@sanseihappa Please stop pinging me. I'll get to it when I get to it.

**Comment by sanseihappa** [comment]
Anything I can do to help out?

**Comment by sanseihappa** [comment]
Possible to revive this? :)

**Comment by cortesi** [comment]
Hi there! This PR conflicts with master. I'll close this for now as part of our general cleanup. Please feel free to rebase this and to resubmit. Pdoc now has a new dev team, and we'll make sure your PR is actioned promptly.

I generally support the direction of this PR - we also want to be able to take pdoc output and integrate it in some reasonable way with our docs. I'm not sure if markdown output is the best way to go for this. It might be that "naked" HTML that can be rendered into a frame might be better. Let's discuss.

**Pull request closed without merging**
