### PR TITLE
Add support for rST field lists, refs #275

### PR DESCRIPTION
**Pull request by mhils**
This PR adds support for field lists for reStructuredText docstrings. 😃 

(CC @talnagar)

### CODE REVIEW

**Comment by talnagar** [comment]
thanks @mhils that's awesome!

**Comment by talnagar** [comment]
how can I install the latest updates? I prefer installing from pypi and not from source. are you planning a release in the near future?

**Comment by talnagar** [comment]
Is there a planned release soon with this PR?

**Comment by mhils** [comment]
You normally should be able to just install from GitHub:
```python
pip install git+https://github.com/mitmproxy/pdoc.git
# or pin a specific commit:
pip install git+https://github.com/mitmproxy/pdoc.git@d2169a3690f07aee138c6ff34f53e5b80fb1a55b
```

I plan to ship a proper release in the next week or two, there are still a few things on my immediate idea list I'd like to include. :)

**Comment by talnagar** [comment]
thanks @mhils I'll wait for the official release. we decided to incorporate pdoc into all of our ci/cd pipelines so we prefer a standard installation. 😄

**Comment by mhils** [comment]
FYI, pdoc 11 is out. :)

**Comment by talnagar** [comment]
thanks @mhils! such an awesome project, I hope to contribute too in the future,

**Pull request merged**
