### PR TITLE
Actually test on latest Pythons

### PR DESCRIPTION
**Pull request by arcivanov**
1) Fix dependencies that did not work
2) Travis harness for building on various Pythons on various platforms
3) Fix mypy errors
4) Fix flake8 errors
5) Add a smoke test for `eating own dogfood`

### CODE REVIEW

**Comment by arcivanov** [comment]
@Kriechi could you please merge and release an new version?  The 0.3.2 in PyPI is not functional on Python 3.5+.

**Comment by arcivanov** [comment]
@timgates42 ?

**Comment by arcivanov** [comment]
@BoboTiG?

**Comment by arcivanov** [comment]
Is this thing on?

**Comment by arcivanov** [comment]
@timgates42 do you know who does and could you tag them please?

**Comment by arcivanov** [comment]
@Kriechi ?

**Comment by Kriechi** [comment]
Thanks for contributing these big CI changes!
I'm not sure how we want to maintain this in the future - for the other projects under the mitmproxy organization we have moved to GitHub Actions - ideally also pdoc would benefit from the same basic structure and integration.

Would you mind splitting out the py35 fix into a smaller PR - this should make it easier to merge and get a release hopefully.

**Comment by arcivanov** [comment]
@Kriechi There are basically no 3.5-specific changes, there are general fixes to make sure the tox tests are passing. I simply bumped down the compatibility after the tests started passing on 3.5 - 3.8.

I think until you guys decide to move to GitHub Actions, you should merge this PR and cut a release that actually works with 3.x, as the current is unusable and it's killing the PDoc plugin for PyBuilder.

**Comment by arcivanov** [comment]
@Kriechi bump?

**Comment by arcivanov** [comment]
@Kriechi bump

**Comment by mhils** [comment]
@arcivanov: Sorry for letting you wait here! Very much appreciated the effort. I've just pushed a major new pdoc release that fixes the issues here and much more. I'll try my best to be much more responsive to new PRs in the future. 😃

**Pull request closed without merging**
