### PR TITLE
Import mistake

### PR DESCRIPTION
**Pull request by SimonL888**
throwed an error "module not found"

### CODE REVIEW

**Comment by mhils** [comment]
The existing code works fine for me and on CI. Could you detail where/how you observed an error?

**Comment by SimonL888** [comment]
> The existing code works fine for me and on CI. Could you detail where/how you observed an error?

On using "import pdoc" i get an error "pygments has not attribute lexers" on Pytjon 3.8.9 after I changed the file it worked again.

**Comment by mhils** [comment]
Which pdoc and pygments version do you have installed? You should be able to figure that out by running `pip freeze`.

**Comment by SimonL888** [comment]
Not sure but could be related to this: [](https://stackoverflow.com/questions/12229580/python-importing-a-sub-package-or-sub-module)

**Comment by mhils** [comment]
Could you try reinstalling pygments and/or pdoc? Are you using plain Python, or some Anaconda/... distribution?

**Comment by mhils** [comment]
fixed in 2cd714543c58823c06b74afdddc3c55e24c31a0d

**Pull request closed without merging**
