### PR TITLE
Recursively evaluate TYPE_CHECKING blocks, fix #648

### LINKED ISSUE #648: `TYPE_CHECKING` warnings when used with Pydantic models
Hello! Thanks (again) for your hard work on `pdoc`.

I'm filing this here since it's the manifestation point, but it _may_ be a bug with Pydantic (or a shared behavioral quirk between the two of them).

#### Problem Description

I'm using `pdoc` to generate HTML documentation for a codebase with a variety of pydantic models, many of which use `Field` to customize their field behavior. 

This causes voluminous warnings when used with `pdoc`, seemingly because `pdoc` fails to evaluate one of `pydantic`'s `TYPE_CHECKING` blocks:

```
Warn: Failed to run TYPE_CHECKING code while parsing dict[str, ComputedFieldInfo] type annotation for bug.Foo.model_computed_fields: cannot import name 'AbstractSetIntStr' from 'pydantic._internal._utils' (/Users/william/tmp/pdoc-bug/env/lib/python3.12/site-packages/pydantic/_internal/_utils.py) (/Users/william/tmp/pdoc-bug/env/lib/python3.12/site-packages/pdoc/doc_types.py:131)
Warn: Error parsing type annotation dict[str, ComputedFieldInfo] for bug.Foo.model_computed_fields. Import of ComputedFieldInfo failed: name 'ComputedFieldInfo' is not defined (/Users/william/tmp/pdoc-bug/env/lib/python3.12/site-packages/pdoc/doc_types.py:147)
Warn: Failed to run TYPE_CHECKING code while parsing dict[str, FieldInfo] type annotation for bug.Foo.__fields__: cannot import name 'AbstractSetIntStr' from 'pydantic._internal._utils' (/Users/william/tmp/pdoc-bug/env/lib/python3.12/site-packages/pydantic/_internal/_utils.py) (/Users/william/tmp/pdoc-bug/env/lib/python3.12/site-packages/pdoc/doc_types.py:131)
Warn: Error parsing type annotation dict[str, FieldInfo] for bug.Foo.__fields__. Import of FieldInfo failed: name 'FieldInfo' is not defined (/Users/william/tmp/pdoc-bug/env/lib/python3.12/site-packages/pdoc/doc_types.py:147)
```

(This is with `bug.py`, which is a minimal reproducer I'll paste below.)

I haven't dug too deeply yet, but the `TYPE_CHECKING` block (in Pydantic) in question doesn't look _too_ unreasonable, besides using quotes for the `TypeAlias` assignment:

```python
if typing.TYPE_CHECKING:
    MappingIntStrAny: TypeAlias = 'typing.Mapping[int, Any] | typing.Mapping[str, Any]'
    AbstractSetIntStr: TypeAlias = 'typing.AbstractSet[int] | typing.AbstractSet[str]'
    from ..main import BaseModel
```

#### Steps to reproduce the behavior:

Minimal reproducer: `bug.py`:

```python
import pydantic

class Foo(pydantic.BaseModel):
    bar: str = pydantic.Field(default="bar")
```

Repro steps:

1. `python -m venv env && source env/bin/activate && python -m pip install pydantic==2.5.2 pdoc==14.1.0 && pdoc bug.py`
2. Observe the warnings on `stderr`

#### System Information

```
pdoc: 14.1.0
Python: 3.12.0
Platform: macOS-14.1.2-arm64-arm-64bit
```

### PR DESCRIPTION
**Pull request by mhils**
/CC @woodruffw - could you verify that this fixes things beyond the MRE? :)

### CODE REVIEW

**Comment by woodruffw** [comment]
> /CC @woodruffw - could you verify that this fixes things beyond the MRE? :)

Trying it now!

**Comment by woodruffw** [comment]
Confirmed! The following produced no warnings:

```bash
pip install https://github.com/mhils/pdoc/archive/type-checking.zip
pdoc my_module
```

**Review by woodruffw — APPROVED** [review]
Thank you for identifying and fixing this so quickly!

**Comment by mhils** [comment]
Awesome, thanks! pdoc 14.2 will be out in a few minutes.

**Pull request merged**
