### PR TITLE
add target to "built-with" link

### PR DESCRIPTION
**Pull request by jacksund**
Adds part 1 of #375 

This simply opens the pdoc website in a new tab when the "built with pdoc" link is selected.

### CODE REVIEW

**Comment by mhils** [comment]
Thanks! 🍰

**Comment by jacksund** [comment]
lol don't thank me yet! Still getting errors. Looks like the snapshots are causing the CI to fail, but I thought I updated them... Is there anything extra I'm missing?

**Comment by mhils** [comment]
Your changes look all right, it might be that the CI image has silently changed. I'll take over from here. :)

**Comment by mhils** [comment]
Actually you do can help me: Do you have `node` or `nodejs` on the system where you regenerated the snapshots?

**Comment by jacksund** [comment]
I'm installing it right now for you. Need me to add my desktop as a CI worker?

**Comment by mhils** [comment]
> I'm installing it right now for you.

Thank you, not necessary! That just confirms my hypothesis on why the snapshots don't match. I'll have a PR momentarily that explains it. 😃

**Comment by jacksund** [comment]
closed in favor of #378

**Pull request closed without merging**
